# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 074d0a5c792aaf0ea616052b3e9be5139a2fa879ed278c1d611f7f2edaa2b87e3fd9daaf5d7abca5d657d6795bfa874ffabaefeb8ab49c5a10b0c2890e155617

test:
  secret_key_base: 47a8e21fb6001fcc3ff1ed552aa7f43d71b1d2f458418f9b384694406cee535ee8983f7f3cbeb847bb0785ce0815cde4b0a7b9398fff847ed32373aa044a60b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
